name: Continuous Integration

permissions:
  contents: read

on:
  push:
    branches: [ master ]
    paths-ignore: [ '.github/**' ]
  pull_request:
    paths-ignore: [ '.github/**' ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Node
        uses: actions/setup-node@v7
        with:
          node-version: lts/*
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run ESlint
        run: npm run lint

      - name: Run Build
        run: npm run build

      - name: Run Tests
        run: npm run test:ci

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f  # v7
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
